$(document).ready(function(){
    $("#employeeNo").val('EMP001')
    $("#dateJoined").val('12/09/2020')
    $("#firstName").val('John')
    $("#lastName").val('Doe')
    $("#gender").val('Male')
    $("#dateOfBirth").val('12/09/1989')
    $("#niNo").val('2098DEM')
    $("#email").val('johndoe@gmail.com')
    $("#phoneNo").val('09087654321')
    $("#paymentMethod#bank").val('Bank')
    $("#paymentMethod#bank").val('Bank')
    $("#studentLoan#no").val('No')
    $("#unionMember#yes").val('No')
    $("#designation").val('Staff')
    $("#address").val('12 Johnson Road')
    $("#city").val('Man City')
    $("#postalCode").val('10106')
    
})