$(document).ready(function(){
    $("#employeeNo").val('EMP001')
    $("#dateJoined").val('12/09/2020')
    $("#firstName").val('John')
    $("#lastName").val('Doe')
    $("#gender").val('Male')
    $("#dateOfBirth").val('12/09/1989')
    $("#niNo").val('SC112233A')
    $("#email").val('johndoe@gmail.com')
    $("#phoneNo").val('09087654321')
    $("#paymentMethod#bank").val('Bank')
    $("#paymentMethod#bank").val('Bank')
    $("#studentLoan#no").val('No')
    $("#unionMember#yes").val('No')
    $("#designation").val('Staff')
    $("#address").val('12 Johnson Road')
    $("#city").val('Man City')
    $("#postalCode").val('10106')
    
})

$(document).ready(function(){
    $("#fullName").val('James Smith')
    $("#niNo").val('SC112233A')
    $("#payMonth").val('April')
    $("#year").val('2019/2020')
    $("#payDay").val('23/03/2019')
    $("#hourlyRate").val('15.00')
    $("#hoursWorked").val('155.00')
    $("#contractualHours").val('144.00')
    $("#overtimeRate").val('22.50')
    $("#overtimeHours").val('11.00')
    $("#taxCode").val('1250L')
    $("#tax").val('273.10')
    $("#nic").val('202.62')
    $("#slc").val('60.00')
    $("#unionFee").val('0.00')
    $("#totalDeduction").val('535.72')
    $("#contractualEarnings").val('2160.00')
    $("#overtimeEarnings").val('247.50')
    $("#totalEarnings").val('2407.50')
    $("#netPayment").val('1871.78')
})